name: CI Pipeline

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x, 20.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci || npm install

            - name: Lint code
              run: npm run lint

            - name: Check formatting
              run: npm run format

            - name: Build
              run: npm run build --if-present

            - name: Run tests
              run: npm test

            - name: Run compatibility test
              run: npm run test:compatibility
